version: "2"
services:
  app:
    build:
      context: ./
    container_name: focalboard
    ports: 
      - 8800:8000
    environment:
      - VIRTUAL_HOST=focalboard.local
      - VIRTUAL_PORT=8000

